version: 0.0
os: linux

files:
  - source: target/todoapp.war
    destination: /opt/tomcat/webapps

permissions:
  - object: scripts
    pattern: "**"
    owner: root
    group: root
    mode: 755

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root
