version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto25
  build:
    commands:
      - mvn clean package

artifacts:
  files:
    - target/*.war
    - appspec.yml
    - scripts/**
